### ISSUE TITLE
KeyError: 'audio'

### ISSUE THREAD

**Issue by CookiePPP** [lmnt-com/wavegrad#2]
`KeyError: 'audio'` in dataloader after 36 iters.
Not sure how this can happen, posting in-case you can see any potential causes while I look myself.

https://github.com/CookiePPP/wavegrad/tree/d0469094947e9cd2c6be1f37e9e948ff58be5560
Exact code used (I don't think any of my modifications would cause the crash).

---

edit:
Crashed again after 214 iters.
Adding some verbosity and running again...

---

```python
CUDA_VISIBLE_DEVICES=3 python3 -m wavegrad "outdir/init" "/media/cookie/Samsung 860 QVO/ClipperDatasetV2"
Epoch 0:   0%|                                        | 0/11466 [00:00<?, ?it/s]/home/cookie/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/cookie/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/cookie/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/cookie/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/cookie/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/cookie/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Epoch 0:   0%|                             | 36/11466 [01:16<3:37:43,  1.14s/it]Traceback (most recent call last):
  File "/home/cookie/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/cookie/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/cookie/Samsung PM961/TwiBot/wavegrad/src/wavegrad/__main__.py", line 37, in <module>
    main(parser.parse_args())
  File "/media/cookie/Samsung PM961/TwiBot/wavegrad/src/wavegrad/__main__.py", line 24, in main
    train(dataset_from_path(args.data_dirs, params), args, params)
  File "/media/cookie/Samsung PM961/TwiBot/wavegrad/src/wavegrad/learner.py", line 151, in train
    learner.train(max_steps=args.max_steps)
  File "/media/cookie/Samsung PM961/TwiBot/wavegrad/src/wavegrad/learner.py", line 94, in train
    for features in tqdm(self.dataset, desc=f'Epoch {self.step // len(self.dataset)}'):
  File "/home/cookie/.local/lib/python3.7/site-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/home/cookie/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/cookie/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 971, in _next_data
    return self._process_data(data)
  File "/home/cookie/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/cookie/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "/home/cookie/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/cookie/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/media/cookie/Samsung PM961/TwiBot/wavegrad/src/wavegrad/dataset.py", line 68, in collate
    audio = np.stack([record['audio'] for record in minibatch if record['audio'] is not None])
  File "/media/cookie/Samsung PM961/TwiBot/wavegrad/src/wavegrad/dataset.py", line 68, in <listcomp>
    audio = np.stack([record['audio'] for record in minibatch if record['audio'] is not None])
KeyError: 'audio'

Epoch 0:   0%|                             | 36/11466 [01:16<6:43:32,  2.12s/it]
```

**Comment by sharvil** [comment]
Oh, I think I know what's going on. That line (and the next one) should probably read:

```python
audio = np.stack([record['audio'] for record in minibatch if 'audio' in record])
spectrogram = np.stack([record['spectrogram'] for record in minibatch if 'spectrogram' in record])
```

That basically means you have an audio clip in the training set that's too short. Once you confirm that the code above fixes it, I'll update the code in `master`.

**Comment by CookiePPP** [comment]
@sharvil 
That resolves the issue in my case.
It still crashes with batch size of 1 (since that would make the spectrograms in the entire batch too short).

**Comment by sharvil** [comment]
Thanks for confirming the fix. If you really want to use such a small batch size, I recommend filtering out all of the .wav files in your dataset that are shorter than the min duration (by default that's `24 frames * 300 samples/frame == 7200 samples`).

**Comment by CookiePPP** [comment]
@sharvil 
I'm filtering them out when initializing the dataset object. :smile:
Thanks for the help!
https://github.com/CookiePPP/wavegrad/commit/1c515f35e829e7e30df78b1288ab64c958e70ec3
